# Generated by Django 5.1.6 on 2025-02-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='preferred_language',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
