# Generated by Django 5.1.6 on 2025-03-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_roommember_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='input_language',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
